import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, existsSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// CSS loader plugin
const cssPlugin = {
	name: 'css',
	setup(build) {
		build.onLoad({ filter: /\.css$/ }, async (args) => {
			const css = readFileSync(args.path, 'utf8');
			return {
				contents: `export default ${JSON.stringify(css)}`,
				loader: 'js',
			};
		});
	},
};

// Path alias plugin
const aliasPlugin = {
	name: 'alias',
	setup(build) {
		build.onResolve({ filter: /^@\// }, args => {
			const relativePath = args.path.slice(2); // 移除 '@/'
			const resolvedPath = path.resolve(__dirname, 'src', relativePath);

			// 尝试添加不同的扩展名
			const extensions = ['.ts', '.tsx', '.js', '.jsx', '.json'];

			for (const ext of extensions) {
				const fullPath = resolvedPath + ext;
				if (existsSync(fullPath)) {
					return { path: fullPath };
				}
			}

			// 如果文件不存在，返回原路径（让 esbuild 自己处理）
			return { path: resolvedPath };
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	platform: "node",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: false,  // Disable tree-shaking to prevent field removal
	minify: false,  // Disable minification
	minifyWhitespace: false,
	minifyIdentifiers: false,
	minifySyntax: false,
	keepNames: true,  // Keep variable names
	outfile: "main.js",
	plugins: [cssPlugin, aliasPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
